import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "sw";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (text: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const swTranslations: Record<string, string> = {
  // Navigation / Common
  "Home": "Nyumbani",
  "Priorities": "Vipaumbele",
  "Foundation": "Taasisi ya Moha",
  "Featured Stories": "Ushuhuda",
  "Top Stories": "Habari Kuu",
  "Polling": "Kura ya Maoni",
  "Advertise With Us": "Tangaza Nasi",
  "Ask Me": "Niulize",
  "Sign In": "Ingia",
  "Donate": "Changia",
  "Donate Now": "Changia Sasa",
  "Support the Movement": "Unga Mkono Harakati",
  "Read the Manifesto": "Soma Ilani",
  "Mathare MP Aspirant • 2027": "Mwaniaji Mbunge wa Mathare • 2027",
  "MOHA": "MOHA",
  "Mathare 2027": "Mathare 2027",
  "Scroll": "Sogeza chini",

  // Homepage Hero
  "Moha Delivers.": "Moha Anawasilisha.",
  "Kuna More na Moha!": "Kuna Zaidi na Moha!",
  "A son of Mathare. A voice for the hustler, the student, the mama, and the mzee.": "Mtoto wa Mathare. Sauti ya hustler, mwanafunzi, mama, na mzee.",
  "Building a constituency where every life matters and every dream has a runway.": "Kujenga eneo bunge ambalo maisha ya kila mmoja ni muhimu na kila ndoto ina nafasi ya kufanikiwa.",
  
  // Activities
  "Daily Campaign Activities": "Shughuli za Kila Siku za Kampeni",
  "Today & Tomorrow": "Leo na Kesho",
  "Where Moha and the team will be on the ground. Activities disappear automatically after the event date.": "Mahali ambapo Moha na timu watakuwa nyanjani. Shughuli hufutika zenyewe baada ya tarehe ya tukio kupita.",
  "No public activities scheduled right now": "Hakuna shughuli za umma zilizoratibiwa kwa sasa",
  "Check back soon — we update this calendar daily.": "Angalia tena baadaye — tunasasisha kalenda hii kila siku.",
  
  // Stats
  "Bursaries Issued": "Bursary Zilizotolewa",
  "Community Projects": "Miradi ya Jamii",
  "Lives Touched": "Maisha Yaliyoguswa",
  "Mathare First": "Mathare Kwanza",
  
  // Pillars
  "Our Four Pillars": "Nguzo Zetu Nne",
  "What Moha is delivering": "Kile Ambacho Moha Anawasilisha",
  "A focused, people-first plan grounded in the realities of Mathare — built with the community, for the community.": "Mpango wenye mwelekeo, unaotanguliza wananchi na unaojikita katika uhalisia wa Mathare — uliojengwa na jamii, kwa ajili ya jamii.",
  "Education": "Elimu",
  "Bursaries, sponsorships & digital learning for every Mathare child.": "Bursary, udhamini na masomo ya kidijitali kwa kila mtoto wa Mathare.",
  "Health & Environment": "Afya na Mazingira",
  "SHA registration, clean rivers, dignified care close to home.": "Usajili wa SHA, mito safi, huduma ya heshima karibu na nyumbani.",
  "Businesses": "Biashara",
  "Capital, infrastructure & security for hustlers and mama mbogas.": "Mtaji, miundombinu na usalama kwa ma-hustler na mama mboga.",
  "Security & Safety": "Usalama na Ulinzi",
  "Safer streets, lit estates, and protection for every household.": "Mitaa salama zaidi, mitaa yenye taa, na ulinzi kwa kila boma.",
  "Explore": "Gundua",
  
  // On the Ground / Gallery
  "On the Ground": "Nyanjani",
  "Real work. Real Mathare.": "Kazi Halisi. Mathare Halisi.",
  "Snapshots from bursary drives, water donations, school visits, and community days — the work that doesn't wait for elections.": "Picha za bursary, misaada ya maji, ziara za shule, na siku za jamii — kazi ambayo haisubiri uchaguzi.",
  
  // Quote
  "Mathare raised me. Now it's my turn to raise Mathare. We don't need promises — we need delivery.": "Mathare alinilea. Sasa ni zamu yangu kuilea Mathare. Hatuhitaji ahadi — tunahitaji utendaji.",
  "Meet the Foundation": "Kutana na Taasisi",
  "Vote on the Issues": "Piga Kura Kuhusu Masuala",

  // Service in Action
  "Service in Action": "Huduma kwa Vitendo",
  "Power the Foundation": "Nguvu kwa Taasisi",
  "The hands behind every delivery": "Marafiki wanaofanikisha kila kazi",
  "Volunteers, organisers and friends of Mathare — showing up week after week.": "Wajitoleaji, waandaaji na marafiki wa Mathare — wanaojitolea wiki baada ya wiki.",
  "Team Moha": "Timu Moha",

  // Foundations List
  "Mama & Mzee Care": "Huduma ya Mama na Mzee",
  "Monthly food parcels, dignity packs, and emergency support for widows, orphans, and elderly residents across all 6 wards of Mathare.": "Vifurushi vya chakula vya kila mwezi, taulo za kike, na msaada wa dharura kwa wajane, yatima, na wazee katika wadi zote 6 za Mathare.",
  "500+ households reached": "Kaya 500+ zimefikiwa",
  "Monthly food & sanitary support drives": "Harakati za kila mwezi za kusambaza chakula na taulo za kike",
  "Emergency shelter for displaced families": "Hifadhi ya dharura kwa familia zilizohamishwa",
  "Mental health & trauma counseling": "Ushauri wa afya ya akili na majeraha ya kisaikolojia",
  "Legal aid for GBV survivors": "Msaada wa kisheria kwa waathiriwa wa GBV",
  "Elderly Persons' Homes": "Nyumba za Wazee",
  "Monthly stipend program for elderly residents": "Mpango wa ruzuku ya kila mwezi kwa wakazi wazee",
  "24/7 GBV rescue & safe-house network": "Mtandaoni wa uokoaji na nyumba salama za GBV za 24/7",

  "Bursaries& Scholarships": "Bursary na Udhamini",
  "Education Fund": "Hazina ya Elimu",
  "From primary school fees to university tuition — Moha's bursary program ensures no Mathare child is locked out of class because of money.": "Kuanzia karo ya shule ya msingi hadi masomo ya chuo kikuu — mpango wa bursary wa Moha unahakikisha hakuna mtoto wa Mathare anayefungiwa nje ya darasa kwa sababu ya pesa.",
  "600+ bursaries issued": "Bursary 600+ zimetolewa",
  "600+ senior school students supported": "Wanafunzi 600+ wa shule za upili wamesaidiwa",
  "60+ students fully sponsored": "Wanafunzi 60+ wamefadhiliwa kikamilifu",
  "School uniforms & textbooks distributed": "Sare za shule na vitabu vya kiada vimesambazwa",
  "Boarding & transport stipends": "Ruzuku ya bweni na usafiri",
  "Mentorship programs sponsored": "Mipango ya ushauri imefadhiliwa",
  "sanitary pads issued to girls": "Taulo za kike zimetolewa kwa wasichana",
  "Overseas & international scholarship pipeline": "Njia ya udhamini wa masomo ya ng'ambo na kimataifa",
  "Mathare alumni mentorship network": "Mtandaoni wa ushauri wa wanachuo wa Mathare",
  "Digital learning labs in every ward": "Vituo vya masomo ya kidijitali katika kila wadi",
  "University and TVET tuition support": "Msaada wa karo ya chuo kikuu na TVET",
  "Job recruitment and industrial attachment opportunities": "Fursa za ajira na mafunzo ya viwandani (attachment)",

  "PWD Inclusion": "Ujumuishaji wa PWD",
  "Accessible Mathare is our promise — wheelchairs, sign-language services, ramps, and economic empowerment for our brothers and sisters living with disabilities.": "Mathare inayofikika ni ahadi yetu — viti vya magurudumu, huduma za lugha ya ishara, njia za mteremko, na uwezeshaji wa kiuchumi kwa ndugu zetu wanaoishi na ulemavu.",
  "350+ PWDs empowered": "PWDs 350+ wamewezeshwa",
  "Free assistive devices (wheelchairs, white canes)": "Vifaa vya kusaidia bure (viti vya magurudumu, fimbo nyeupe)",
  "PWD entrepreneur grants": "Ruzuku kwa wajasiriamali walemavu (PWD)",
  "Regular assistive devices rollout": "Usambazaji wa mara kwa mara wa vifaa vya kusaidia",
  "PWD-friendly vocational training centre": "Kituo cha mafunzo ya kazi kinachofaa walemavu",
  "Inclusive sports league for PWDs": "Ligi ya michezo jumuishi kwa walemavu",
  "Sign-language interpreters at events": "Wakalimani wa lugha ya ishara kwenye hafla",

  "Team Moha on the Ground": "Timu Moha Nyanjani",
  "Mentorship circles, skills bootcamps, and community drives that put Mathare's youth at the centre of every action — because the future is already here.": "Vikundi vya ushauri, mafunzo ya ujuzi, na kampeni za jamii zinazoweka vijana wa Mathare katikati ya kila hatua — kwa sababu maisha ya baadaye tayari yameanza.",
  "5,000+ youth mobilised": "Vijana 5,000+ wamehamasishwa",
  "Door-to-door community mobilisation": "Uhamasishaji wa jamii mlango kwa mlango",
  "Leadership & mentorship circles": "Vikundi vya uongozi na ushauri",
  "Civic education and voter awareness": "Elimu ya uraia na uelewa wa wapiga kura",
  "Volunteer & internship pipeline": "Njia ya kujitolea na mafunzo ya kazi (internship)",
  "Recruitment & industrial attachment opportunities": "Fursa za kuajiriwa na mafunzo ya viwandani",
  "Youth innovation hub with free Wi-Fi": "Kituo cha uvumbuzi cha vijana chenye Wi-Fi ya bure",
  "Annual Mathare youth leadership summit": "Mkutano wa kilele wa kila mwaka wa uongozi wa vijana wa Mathare",
  "Expanding Moha's Biz Mtaani initiatives": "Kupanua mipango ya Moha ya Biz Mtaani",

  "Mathare Plays": "Mathare Inacheza",
  "From dusty pitches to medal podiums — Moha sponsors tournaments, kits, prizes, and cheers loudest when Mathare's talented kids take the stage.": "Kuanzia nyanja zenye vumbi hadi majukwaa ya medali — Moha anafadhili mashindano, vifaa, zawadi, na kushangilia kwa nguvu wakati watoto wenye vipaji wa Mathare wanaposhiriki.",
  "3+ tournaments backed": "Mashindano 3+ yamefadhiliwa",
  "Ladies tournaments": "Mashindano ya akina dada",
  "Trophies and medal": "Trophy na medali",
  "Adults' fun day": "Siku ya kujifurahisha ya watu wazima",
  "More organized grassroot sports with cash prizes": "Michezo iliyoratibiwa zaidi ya mashinani yenye zawadi za pesa",
  "Talent academy for music, dance & arts": "Akademia ya vipaji ya muziki, densi na sanaa",
  "Modern community sports complex": "Uwanja wa kisasa wa michezo wa jamii",

  "Books, Pens & More": "Vitabu, Kalamu na Mengi Zaidi",
  "Textbooks, exercise books, pens, rulers and full stationery kits delivered straight to learners — so the only thing standing between a child and class is their dream.": "Vitabu vya kiada, vitabu vya mazoezi, kalamu, rula na vifaa kamili vya uandishi vinavyofikishwa moja kwa moja kwa wanafunzi — ili kitu pekee kinachosimama kati ya mtoto na darasa kiwe ndoto yake.",
  "1,000+ supplies distributed": "Vifaa 1,000+ vimesambazwa",
  "Exercise books, pens, pencils & rulers": "Vitabu vya mazoezi, kalamu, penseli na rula",
  "Full back-to-school textbooks and stationery kits": "Vitabu kamili vya kurudi shule na vifaa vya uandishi",
  "Sponsorship from suppliers": "Udhamini kutoka kwa wasambazaji",
  "Community library in every ward": "Maktaba ya jamii katika kila wadi",
  "Termly stationery restock drives": "Kampeni za kila muhula za kuongeza vifaa vya uandishi",
  "Job opportunities and industrial attachment from suppliers and publishers": "Fursa za kazi na mafunzo kutoka kwa wasambazaji na wachapishaji",

  "Hustlers First": "Hustlers Kwanza",
  "Moha's team walks the markets — from mama mbogas to boda riders — backing the small businesses that keep Mathare moving.": "Timu ya Moha inatembea masokoni — kuanzia kwa mama mboga hadi waendeshaji boda — ikisaidia biashara ndogo ndogo zinazoweka Mathare katika mwendo.",
  "1,800+ hustlers supported": "Ma-hustler 1,800+ wamesaidiwa",
  "Capital boosts for mama mbogas & kiosks": "Nyongeza ya mtaji kwa mama mboga na vibanda",
  "Equipment & stock support": "Msaada wa vifaa na bidhaa",
  "Visibility on the Mathare Business Hub": "Kuonekana kwenye Kituo cha Biashara cha Mathare",
  "Mentorship for youth-led startups": "Ushauri kwa biashara changa zinazoongozwa na vijana",
  "Low-interest revolving credit fund": "Hazina ya mkopo inayozunguka ya riba nafuu",
  "Modern market stalls & cold storage": "Vibanda vya soko vya kisasa na bohari ya baridi",
  "Business skills bootcamps for hustlers": "Mafunzo makali ya ujuzi wa biashara kwa ma-hustler",
  "Mentorship and market growth through adverts": "Ushauri na ukuaji wa soko kupitia matangazo",

  "ECD & Kids": "ECD na Watoto",
  "Safe, nurturing learning spaces for our youngest — because the journey to a transformed Mathare begins in the ECD classroom.": "Maeneo salama na yenye kulelea masomo kwa wadogo zetu — kwa sababu safari ya kugeuza Mathare inaanza katika darasa ya ECD.",
  "30+ ECD centres reached": "Vituo vya ECD 30+ vimefikiwa",
  "Learning materials and play kits": "Vifaa vya kujifunzia na vifaa vya kuchezea",
  "Nutrition support for young learners": "Msaada wa lishe kwa wanafunzi wadogo",
  "More learning materials and play kits": "Vifaa zaidi vya kujifunzia na vya kuchezea",
  "Upgraded playgrounds and pitches": "Viwanja vilivyoboreshwa vya michezo na kuchezea",
  "Caregiver training & certification": "Mafunzo na uthibitisho wa walezi",
  "Caregiver & teacher support": "Msaada kwa walezi na walimu",

  // CTA Cards
  "Ask Moha": "Muulize Moha",
  "Your questions deserve answers. Send a question directly to Moha.": "Maswali yako yanastahili majibu. Tuma swali moja kwa moja kwa Moha.",
  "Ask now": "Uliza sasa",
  "Share Your Opinion": "Toa Maoni Yako",
  "Tell us what Mathare needs. Every voice shapes the manifesto.": "Tueleze kile Mathare inahitaji. Kila sauti inaunda ilani.",
  "Send a message": "Tuma ujumbe",

  // Priorities Page & Tabs
  "Our Priorities": "Vipaumbele Vyetu",
  "Education, Health, Business, Environment.": "Elimu, Afya, Biashara, Mazingira.",
  "Key Challenges We Must Solve": "Changamoto Kuu Tunazopaswa Kutatua",
  "What We Have Done": "Kile Tulichofanya",
  "Our Future Roadmap": "Mipango Yetu ya Baadaye",
  "Every child reads. Every dream is funded.": "Kila mtoto anasoma. Kila ndoto inafadhiliwa.",
  "Clean Mathare. Healthy Mathare. Dignified care.": "Mathare Safi. Mathare Yenye Afya. Huduma ya Heshima.",
  "Empowering local businesses, mama mbogas, and youth hubs.": "Kuwezesha biashara za ndani, mama mboga, na vitovu vya vijana.",
  "Ensuring safety and security for all residents.": "Kuhakikisha usalama na ulinzi kwa wakazi wote.",
  "Supporting other community and development initiatives.": "Kusaidia mipango mingine ya jamii na maendeleo.",

  // Challenges/Initiatives/Future for Education
  "Fee challenges": "Changamoto za karo za shule",
  "Undeveloped infrastructure": "Miundombinu duni",
  "Inadequate digital penetration/ICT": "Ukosefu wa vifaa vya kidijitali/Teknolojia",
  "Shortage of teachers": "Upungufu wa walimu",
  "Few public schools": "Shule chache za umma",
  "High dropout rates": "Kiwango kikubwa cha wanafunzi wanaoacha shule",
  "Unsafe learning environment": "Mazingira yasiyo salama ya kusomea",
  "Inadequate food/malnutrition": "Chakula kisichotosha/Utapiamlo",
  "Severe Overcrowding in classes": "Msongamano mkubwa darasani",
  "600+ bursaries issued to needy students": "Bursary 600+ zimetolewa kwa wanafunzi wenye mahitaji",
  "Over 60 students fully sponsored": "Zaidi ya wanafunzi 60 wamedhaminiwa kikamilifu",
  "Food donation to needy households": "Msaada wa chakula kwa kaya zenye mahitaji",
  "Feeding program to school children": "Mpango wa chakula kwa watoto wa shule",
  "Empowerment programs to parents and guardians to get income": "Mipango ya uwezeshaji kwa wazazi na walezi kupata kipato",
  "Tuition organized for pre-primary, junior and senior students": "Masomo ya ziada kwa wanafunzi wa chekechea na sekondari",
  "Sanitary pads/towels to girls": "Taulo za kike (sodo) kwa wasichana",
  "Legal education to parents and guardians": "Elimu ya kisheria kwa wazazi na walezi",
  "Back to school sports tournaments": "Mashindano ya michezo ya kurudi shule",
  "Distribution of stationeries/books to students": "Usambazaji wa vitabu na vifaa vya kuandikia",
  "Bought and distributed uniforms and boarding items to needy students": "Kununua na kusambaza sare na vifaa vya bweni kwa wanafunzi wenye mahitaji",
  "Add more bursary allocation to all wards": "Kuongeza mgao wa bursary katika wadi zote",
  "Build more schools and upgrade the current ones": "Kujenga shule zaidi na kuboresha zilizopo sasa",
  "Establish digital learning centers in each ward": "Kuanzisha vituo vya masomo ya kidijitali katika kila wadi",
  "Source for more teachers from TSC": "Kutafuta walimu zaidi kutoka TSC",
  "Clear drainage and enhance security near learning centers": "Kusafisha mifereji na kuimarisha usalama karibu na shule",
  "Enhance school feeding programs": "Kuboresha mipango ya chakula mashuleni",

  // Challenges/Initiatives/Future for Health
  "Poor waste management": "Usimamizi duni wa taka",
  "Uncollected garbage": "Taka zisizozolewa",
  "Flooding during heavy rains": "Mafuriko wakati wa mvua kubwa",
  "Stagnant dirty water": "Maji machafu yaliyotuama",
  "Poor sanitation and drainage systems": "Mifumo duni ya usafi na mifereji ya maji",
  "Dirty water from sewer bursts": "Maji machafu kutoka kwa mabomba ya maji taka yaliyopasuka",
  "Inadequate clean/safe drinking water": "Ukosefu wa maji safi na salama ya kunywa",
  "Few healthcare centers": "Vituo vichache vya afya",
  "High cost of treatment": "Gharama kubwa ya matibabu",
  "Drug accessibility challenges": "Changamoto za kupata dawa",
  "NHIF/SHIF registration drives to help needy households access treatment": "Usajili wa NHIF/SHIF kusaidia kaya yenye mahitaji kupata matibabu",
  "Medical camps in Huruma and Mathare North": "Kambi za matibabu huko Huruma na Mathare Kaskazini",
  "Support for community health workers with stipends": "Msaada na marupurupu kwa wahudumu wa afya wa jamii",
  "Clean-up drives across Mathare River and local estates": "Harakati za kusafisha Mto Mathare na mitaa ya karibu",
  "Distribution of water tanks and clean drinking water to residents": "Usambazaji wa matanki na maji safi ya kunywa kwa wakazi",
  "Construct modern public clinics in every ward": "Kujenga zahanati za kisasa katika kila wadi",
  "Implement a sustainable garbage recycling program": "Kuanzisha mpango endelevu wa kurejesha taka (recycling)",
  "Establish mobile health clinics for quick response": "Kuanzisha kliniki zinazotembea kwa ajili ya huduma za haraka",
  "Collaborate with county government to fix drainage systems": "Kushirikiana na serikali ya kaunti kurekebisha mifumo ya maji taka",

  // Challenges/Initiatives/Future for Businesses
  "Lack of capital/business funds": "Ukosefu wa mtaji au fedha za biashara",
  "High interest rates on loans": "Viwango vya juu vya riba kwenye mikopo",
  "Harassment by county askaris": "Kusumbuliwa na askari wa kaunti (kanjo)",
  "Poor market infrastructure": "Miundombinu duni ya masoko",
  "Insecurity and theft of stock": "Ukosefu wa usalama na wizi wa bidhaa",
  "Lack of business skills/financial literacy": "Ukosefu wa ujuzi wa biashara au usimamizi wa fedha",
  "Established a Mama Mboga capital fund targeting KSh 50M": "Kuanzisha mfuko wa mtaji wa Mama Mboga wenye lengo la KSh 50M",
  "Youth business grants and mentorship programs": "Ruzuku za biashara kwa vijana na mipango ya ushauri",
  "Setup secure storage hubs for local traders": "Kuweka vituo salama vya kuhifadhia bidhaa za wafanyabiashara",
  "Financial literacy workshops for market vendors": "Warsha za usimamizi wa fedha kwa wachuuzi wa masoko",
  "Provide interest-free mini-loans to registered small businesses": "Kutoa mikopo midogo isiyo na riba kwa biashara ndogo zilizosajiliwa",
  "Build modern, covered markets with clean running water": "Kujenga masoko ya kisasa yenye maji safi ya kutiririka",
  "Advocate for fairer bylaws to protect small traders": "Kutetea sheria ndogo za haki ili kulinda wafanyabiashara wadogo",
  "Facilitate business registration and SACCO formations": "Kusaidia usajili wa biashara na uundaji wa SACCO",

  // Challenges/Initiatives/Future for Security
  "Dark streets/estates leading to muggings": "Mitaa yenye giza inayosababisha kuporwa",
  "Slow police response times": "Polisi kuchelewa kujibu dharura",
  "Drug and substance abuse among youth": "Matumizi ya dawa za kulevya miongoni mwa vijana",
  "Gangs and criminal networks": "Magenge ya wahalifu",
  "High rates of gender-based violence (GBV)": "Viwango vya juu vya unyanyasaji wa kijinsia (GBV)",
  "Installed solar-powered streetlights in crime hotspots": "Kuweka taa za barabarani zinazotumia umeme wa jua kwenye maeneo hatari",
  "Supported community policing forums and youth groups": "Kusaidia vikundi vya usalama vya jamii (community policing) na vijana",
  "Established a GBV rescue and legal counseling center": "Kuanzisha kituo cha uokoaji na ushauri wa kisheria kwa waathiriwa wa GBV",
  "Organized youth sensitization and drug rehabilitation programs": "Kuandaa mipango ya kuhamasisha vijana na kurekebisha watumiaji wa dawa za kulevya",
  "Expand street lighting project to cover all corners of Mathare": "Kupanua mradi wa taa za barabarani kufunika pembe zote za Mathare",
  "Lobby for more police posts and improved patrol infrastructure": "Kushawishi uwepo wa vituo vya polisi zaidi na doria bora",
  "Set up a drug rehab center within Mathare": "Kujenga kituo cha kurekebisha tabia (rehab) ndani ya Mathare",
  "Provide sports and alternative livelihoods to keep youth away from crime": "Kutoa michezo na njia mbadala za kujipatia riziki ili kuwaepusha vijana na uhalifu",

  // Challenges/Initiatives/Future for Others
  "Lack of youth engagement and talent promotion": "Ukosefu wa ushirikiano na kukuza vipaji vya vijana",
  "Poor public spaces for community meetings": "Ukosefu wa maeneo ya umma kwa ajili ya mikutano ya jamii",
  "Limited access to legal support for vulnerable residents": "Upatikanaji mdogo wa usaidizi wa kisheria kwa wakazi wanyonge",
  "High youth unemployment rates": "Kiwango cha juu cha ukosefu wa ajira kwa vijana",
  "Hosted the annual Moha Delivers sports tournament": "Kuandaa mashindano ya kila mwaka ya michezo ya Moha Delivers",
  "Constructed a community social hall": "Kujenga ukumbi wa kijamii wa mikutano",
  "Free legal aid clinics for land and civil disputes": "Kliniki za msaada wa kisheria bila malipo kwa migogoro ya ardhi na kiraia",
  "Partnerships with TVET institutes for technical skills training": "Ushirikiano na vyuo vya TVET kwa mafunzo ya kiufundi",
  "Establish a fully equipped youth talent center and recording studio": "Kuanzisha kituo chenye vifaa kamili cha vipaji vya vijana na studio ya kurekodia",
  "Launch a constituency innovation hub for tech and remote work": "Kuzindua kituo cha uvumbuzi cha eneo bunge kwa ajili ya kazi za teknolojia na mtandaoni",
  "Partner with local financial institutions for affordable youth credit": "Kushirikiana na taasisi za kifedha kwa ajili ya mikopo nafuu kwa vijana",

  // Foundations Page Sections
  "Vulnerable Groups": "Vikundi Vilivyo Kwenye Hatari",
  "Bursary Program": "Mpango wa Bursary",
  "People with Disabilities": "Watu Wenye Ulemavu",
  "Empowering over 8,500 households with food, dignity packs, and legal aid.": "Kuwezesha zaidi ya kaya 8,500 kwa chakula, vifurushi vya utu, na msaada wa kisheria.",
  "Supporting education from primary to university with over 12,000 bursaries issued.": "Kusaidia elimu kuanzia shule ya msingi hadi chuo kikuu na zaidi ya bursary 12,000 zilizotolewa.",
  "Providing tools, grants, and accessible spaces to empower over 1,200 PWDs.": "Kutoa zana, ruzuku, na maeneo yanayofikika ili kuwezesha watu wenye ulemavu zaidi ya 1,200.",
  "Apply for Bursary": "Omba Bursary",
  "Bursary Application Form": "Fomu ya Maombi ya Bursary",
  "The bursary application window is currently closed.": "Muda wa maombi ya bursary umefungwa kwa sasa.",
  "Applications open on": "Maombi yatafunguliwa mnamo",
  "Check back soon for updates.": "Angalia tena hivi karibuni kwa habari zaidi.",
  "Youth & Women": "Vijana na Wanawake",
  "Sports & Talent Development": "Maendeleo ya Michezo na Vipaji",
  "Community Empowerment Projects": "Miradi ya Uwezeshaji Jamii",
  "ECD & School Supplies Support": "Msaada wa Vifaa vya Shule na ECD",
  "See Details": "Angalia Maelezo",
  "Open Form": "Fungua Fomu",
  "Close": "Funga",

  // Forms & Inputs
  "Your Name": "Jina Lako",
  "Phone Number": "Nambari ya Simu",
  "Your Question": "Swali Lako",
  "Submit Question": "Tuma Swali",
  "Submitting...": "Inatuma...",
  "Select your Ward": "Chagua Wadi yako",
  "Your Message": "Ujumbe Wako",
  "Submit Opinion": "Tuma Maoni",
  "Thank you! Your message has been sent successfully.": "Asante! Ujumbe wako umetumwa kwa mafanikio.",
  "We will get back to you if needed.": "Tutawasiliana nawe ikihitajika.",
  "Send another message": "Tuma ujumbe mwingine",
  "Choose your ward": "Chagua wadi yako",
  "Type your message here...": "Andika ujumbe wako hapa...",
  "Type your question here...": "Andika swali lako hapa...",
  "Enter your phone number...": "Weka nambari yako ya simu...",
  "Enter your name...": "Weka jina lako...",
  
  // Wards
  "Mabatini": "Mabatini",
  "Huruma": "Huruma",
  "Hospital": "Hospital",
  "Kiamaiko": "Kiamaiko",
  "Ngei": "Ngei",
  "Mlango Kubwa": "Mlango Kubwa",

  // Polling
  "Community Polls": "Kura za Maoni za Jamii",
  "Your Voice Matters": "Sauti Yako ni Muhimu",
  "Vote on key community issues to help Moha build a better Mathare.": "Piga kura juu ya masuala muhimu ya jamii ili kumsaidia Moha kujenga Mathare bora.",
  "Polls": "Kura za Maoni",
  "Select Ward to Vote": "Chagua Wadi ili Upige Kura",
  "Submit Vote": "Tuma Kura",
  "Reset Poll": "Weka Upya Kura",
  "Total Votes": "Jumla ya Kura",
  "You voted!": "Umeshapiga kura!",
  "Thank you for voting.": "Asante kwa kupiga kura.",
  "Your Voice": "Sauti Yako",
  "Vote on what matters": "Piga kura juu ya masuala muhimu",
  "Pick your Mathare ward, then tell Moha where you stand. Every vote shapes the action plan.": "Chagua wadi yako ya Mathare, kisha umweleze Moha msimamo wako. Kila kura inaunda mpango wa utekelezaji.",
  "Step 1 — Select your ward": "Hatua ya 1 — Chagua wadi yako",
  "We use this only to break results down by ward. One vote per question per device.": "Tunatumia hii tu kupanga matokeo kulingana na wadi. Kura moja kwa kila swali kwa kila kifaa.",
  "Choose your Mathare ward": "Chagua wadi yako ya Mathare",
  "Voting as a resident of": "Unapiga kura kama mkazi wa wadi ya",
  "ward": "ward",
  "Rate how the following services are offered in Mathare by the Government and people's Representatives": "Kadiria jinsi huduma zifuatazo zinavyotolewa Mathare na Serikali na Wawakilishi wa wananchi",
  "Click a rating, then tick the services it applies to. One vote per service per device.": "Bonyeza kadirio, kisha uweke alama kwenye huduma zinazohusika. Kura moja kwa kila huduma kwa kila kifaa.",
  "↑ Select your ward above to unlock voting.": "↑ Chagua wadi yako hapo juu ili uweze kupiga kura.",
  "Select your ward above to unlock voting.": "Chagua wadi yako hapo juu ili uweze kupiga kura.",
  "Results are kept private and shared with Moha's team only.": "Matokeo huwekwa siri na kushirikiwa na timu ya Moha pekee.",
  "Asante! Your vote from {ward} ward has been recorded.": "Asante! Kura yako kutoka wadi ya {ward} imerekodiwa.",
  "Asante sana for voting! 🙏": "Asante sana kwa kupiga kura! 🙏",
  "Enter your mobile number to receive a thank-you message with a link you can share with friends.": "Weka nambari yako ya simu ili upokee ujumbe wa shukrani wenye kiungo unachoweza kushiriki na marafiki.",
  "Message sent to {phone}!": "Ujumbe umetumwa kwa {phone}!",
  "Share the link with your friends so they can also have their say.": "Shiriki kiungo hiki na marafiki zako ili nao pia watoe maoni yao.",
  "The SMS will include a link to": "SMS itajumuisha kiungo cha",
  "that you can forward to friends and family. Standard Safaricom / Airtel rates may apply.": "ambacho unaweza kusambaza kwa marafiki na familia. Ushuru wa kawaida wa Safaricom / Airtel unaweza kutozwa.",
  "Have a different idea? Send a message": "Je, una wazo tofauti? Tuma ujumbe",
  "voted": "kura zilizopigwa",
  "Rated": "Imekadiriwa",
  
  // Polling questions & options
  "What is the #1 issue Mathare needs solved first?": "Ni changamoto gani kuu inayopaswa kutatuliwa kwanza hapa Mathare?",
  "Education funding": "Ufadhili wa elimu",
  "Pollution and waste management": "Uchafuzi wa mazingira na usimamizi wa taka",
  "Drainage and flooding": "Mifereji ya maji na mafuriko",
  "Insecurity and safety": "Ukosefu wa usalama",
  "Financial constraints and credits inaccessibility": "Changamoto za kifedha na kutopata mikopo",
  "Crime, rape and GBV": "Uhalifu na unyanyasaji wa kijinsia",
  "Youth unemployment": "Ukosefu wa ajira kwa vijana",
  "Which education program should we expand next?": "Je, ni mpango gani wa elimu tunaopaswa kuupanua baadaye?",
  "University tuition fund": "Mfuko wa karo ya chuo kikuu",
  "Digital learning labs": "Vituo vya masomo ya kidijitali",
  "TVET scholarships": "Udhamini wa masomo ya TVET (vyuo vya ufundi)",
  "Adult literacy classes": "Masomo ya kusoma na kuandika kwa watu wazima",
  "High school Bursaries and scholarships": "Bursary na udhamini wa shule za upili",
  "How strongly do you agree with Moha's initiatives & projects in Mathare?": "Je, unakubaliana kwa kiasi gani na miradi na mipango ya Moha hapa Mathare?",
  "Strongly agree": "Nakubaliana kabisa",
  "Agree": "Nakubaliana",
  "Neutral": "Sina upande",
  "Disagree": "Sikubaliani",
  "Strongly disagree": "Sikubaliani kabisa",
  "Is Moha the best candidate for Mathare MP in 2027?": "Je, Moha ndiye mgombea bora wa ubunge Mathare mwaka 2027?",
  "Yes — he's the best option": "Ndiyo — yeye ndiye chaguo bora zaidi",
  "Likely yes": "Pengine ndiyo",
  "Undecided": "Bado sijaamua",
  "Likely no": "Pengine hapana",
  "No": "Hapana",
  
  // Service ratings
  "How do you rate Moha's delivery on Education?": "Unaonaje utendaji wa Moha katika sekta ya Elimu?",
  "How do you rate Moha's delivery on Health?": "Unaonaje utendaji wa Moha katika sekta ya Afya?",
  "How do you rate Moha's delivery on Security?": "Unaonaje utendaji wa Moha katika sekta ya Usalama?",
  "How do you rate Moha's delivery on Business Support?": "Unaonaje utendaji wa Moha katika sekta ya Kusaidia Biashara?",
  "How do you rate Moha's delivery on All Services Overall?": "Unaonaje utendaji mzima wa Moha katika huduma zote kwa ujumla?",
  "How do you rate Moha's delivery on Other (None of the above)?": "Unaonaje utendaji wa Moha katika sekta Nyinginezo?",
  "Best": "Bora Zaidi",
  "Fairly": "Wastani",
  "Worst": "Mbaya Zaidi",

  // Ask & Opinion Pages
  "Direct Line": "Njia ya Moja kwa Moja",
  "Ask Moha anything.": "Muulize Moha chochote.",
  "No filters. No PR speak. Submit your question and get a real answer from Moha or his team.": "Hakuna vichungi. Hakuna maneno ya urembo. Tuma swali lako na upate jibu halisi kutoka kwa Moha au timu yake.",
  "Phone or Email": "Simu au Barua Pepe",
  "07XX or you@email.com": "07XX au barua@pepe.com",
  "Ask Moha…": "Muulize Moha...",
  "Popular questions": "Maswali yanayoulizwa mara kwa mara",
  "Tip: try the floating chat (bottom-right) for instant manifesto answers from Moha's AI.": "Kidokezo: jaribu soga inayoelea (chini kulia) kwa majibu ya haraka ya ilani kutoka kwa AI ya Moha.",
  "What's your plan for youth unemployment?": "Una mpango gani kuhusu ukosefu wa kazi kwa vijana?",
  "How will you handle insecurity in Mathare?": "Utashughulikia vipi ukosefu wa usalama Mathare?",
  "Where can I find your full manifesto?": "Ninaweza kupata wapi ilani yako kamili?",
  "How do I volunteer for the campaign?": "Ninajitolea vipi kwa ajili ya kampeni?",
  "What is the bursary application process?": "Utaratibu wa kuomba bursary uko vipi?",
  "Question received! Moha or his team will get back to you.": "Swali limepokelewa! Moha au timu yake watawasiliana nawe.",
  "Speak Up": "Sema Upate Kusikika",
  "Your message. Real action.": "Ujumbe wako. Hatua halisi.",
  "Tell us what Mathare needs — ideas, complaints, suggestions, encouragement. Moha's team reads every single message.": "Tueleze kile Mathare inahitaji — mawazo, malalamiko, mapendekezo, au motisha. Timu ya Moha inasoma kila ujumbe.",
  "Ward / Estate": "Wadi / Mtaa",
  "e.g. Mlango Kubwa": "mfano Mlango Kubwa",
  "Tell Moha what's on your mind…": "Mweleze Moha kilicho moyoni mwako...",
  "Send to Moha": "Tuma kwa Moha",
  "Sending…": "Inatuma...",
  "Asante! Your message has reached Moha's team.": "Asante! Ujumbe wako umefika kwa timu ya Moha.",
  "4-step application": "maombi ya hatua 4",
  "Window closes": "Muda unafungwa",
  "Coming Soon": "Inakuja Hivi Karibuni",
  "Applications are currently closed": "Maombi yamefungwa kwa sasa",
  "The bursary application window is not open at the moment. Check back soon or follow our social media for the next opening date.": "Muda wa maombi ya bursary haujafunguliwa kwa sasa. Angalia tena hivi karibuni au fuata mitandao yetu ya kijamii kwa tarehe ya ufunguzi unaofuata.",

  // Priorities page column headers & subtitles
  "Challenges": "Changamoto",
  "Initiatives": "Mipango",
  "Future Plans": "Mipango ya Baadaye",
  "What Mathare faces today": "Kinachokabiliwa na Mathare Leo",
  "What Moha is already delivering": "Kinachotekelezwa tayari na Moha",
  "What we will deliver next": "Tutakachotekeleza baadaye",
  "Support programs already running": "Mipango ya msaada inayoendelea",
  "New opportunities on the way": "Fursa mpya zinazokuja",
  "The Manifesto": "Ilani",
  "Other Initiatives": "Mipango Mingine",

  // Priorities challenges/initiatives (health, businesses, security, other)
  "Flooding": "Mafuriko",
  "poor planning": "mipango mibaya",
  "Water and air polution": "Uchafuzi wa maji na hewa",
  "Waterbone and respiratory diseases": "Magonjwa ya maji na njia za hewa",
  "poor sanitation": "usafi duni",
  "Mental health and drug abuse": "Afya ya akili na matumizi ya dawa za kulevya",
  "Food distribution to needy households to improve nutrition": "Usambazaji wa chakula kwa kaya zenye mahitaji kuboresha lishe",
  "cleaning exercise done in each ward": "Zoezi la usafi limefanywa katika kila wadi",
  "Water distribution during scarcity": "Usambazaji wa maji wakati wa uhaba",
  "SHA registration and payments to needy families and empowerments of youths to shurn drug abuse and violence": "Usajili wa SHA na malipo kwa familia zenye mahitaji na uwezeshaji wa vijana ili kuepuka matumizi ya dawa za kulevya na vurugu",
  "Sanitary towels/pads to girls": "Taulo za kike kwa wasichana",
  "distribution of wheelchairs and other essential ammenities to the PWDs": "Usambazaji wa viti vya magurudumu na vitu muhimu kwa watu wenye ulemavu",
  "distribution of essentials to families affected by floods": "Usambazaji wa mahitaji ya msingi kwa familia zilizoathiriwa na mafuriko",
  "Support for people living with chronic illnesses": "Msaada kwa watu wanaoishi na magonjwa ya kudumu",
  "Liase with County Government to push for cleaning programs of Mathare and the rivers": "Kushirikiana na Serikali ya Kaunti kushinikiza mipango ya usafi wa Mathare na mito",
  "Empower CBOs and individuals in waste managementand disposal": "Kuwezesha Vikundi vya Jamii na watu binafsi katika usimamizi na utupaji wa taka",
  "Open drainage systems and build more roads to estates and houses": "Kufungua mifumo ya mifereji na kujenga barabara zaidi kwenye makazi na nyumba",
  "Establish Mental health and drug abuse rehabilitation centers in Mathare": "Kuanzisha vituo vya ukarabati wa afya ya akili na uraibu wa dawa za kulevya Mathare",
  "Register more households/families to SHA and other insuarances": "Kusajili kaya na familia zaidi katika SHA na bima nyingine",
  "To push the County and National Govenments to order for proper planning to mitigate against floods": "Kushinikiza Serikali za Kaunti na Taifa kuagiza mipango sahihi ya kupunguza mafuriko",
  "Finacial constraints and credit accessibility": "Vikwazo vya kifedha na upatikanaji wa mikopo",
  "poor infrastructure and utilities": "miundombinu duni na huduma mbaya",
  "Insecurity and Safety of businesses": "Ukosefu wa usalama kwa biashara",
  "Inadequate business support and education": "Msaada duni wa biashara na elimu",
  "Low purchasing power and crowded markets": "Nguvu ndogo ya ununuzi na masoko yaliyosongamana",
  "Fundraising in aid of businesses, groups and individuals": "Kukusanya fedha kusaidia biashara, vikundi na watu binafsi",
  "Empowerment of programs to women, youth and entrepreneurs": "Uwezeshaji wa mipango kwa wanawake, vijana na wajasiriamali",
  "Buying handcarts to groups and youths": "Kununua mikokoteni kwa vikundi na vijana",
  "Donating of chair and tents to groups": "Kuchangia viti na hema kwa vikundi",
  "Construction of bodaboda tents/shede": "Ujenzi wa hema/vibanda vya bodaboda",
  "Buying TV sets and DStv to youth groups": "Kununua vifaa vya TV na DStv kwa vikundi vya vijana",
  "Providing raincoats to businesses": "Kutoa koti za mvua kwa wafanyabiashara",
  "Buying water tanks and car wash machines to youth groups": "Kununua matanki ya maji na mashine za kuosha magari kwa vikundi vya vijana",
  "Equiping barber and salon shops": "Kuvifaa maduka ya kinyozi na saluni",
  "Buying boxing equipment and materials to youth groups": "Kununua vifaa vya masumbwi kwa vikundi vya vijana",
  "Providing umbrellas to businesses": "Kutoa miavuli kwa wafanyabiashara",
  "Building stocks for businesses e.g omena and eggs": "Kujenga hifadhi ya bidhaa kwa biashara k.m omena na mayai",
  "Expand financial inclusion and source for more funds from reliable partners": "Kupanua ushirikiano wa kifedha na kutafuta fedha zaidi kutoka kwa washirika wa kuaminika",
  "Improve the drainage, streets, lighting, roads accessibility and expand more market stalls": "Kuboresha mifereji, mitaa, taa, upatikanaji wa barabara na kupanua vibanda zaidi vya soko",
  "Enhance security by collaborating with National Govenment to build more police posts and add more security personnel": "Kuimarisha usalama kwa kushirikiana na Serikali ya Taifa kujenga vituo zaidi vya polisi na kuongeza maafisa wa usalama",
  "Organize business training and education to established and upcoming entrepreneurs": "Kupanga mafunzo ya biashara kwa wajasiriamali waliopo na wanaokuja",
  "Create more empowerment programs to improve the purchasing power.": "Kuunda mipango zaidi ya uwezeshaji kuboresha nguvu ya ununuzi",
  "Violence, crime and gang activities": "Vurugu, uhalifu na shughuli za magenge",
  "GBV and rape": "GBV na ubakaji",
  "Unemployment and poverty": "Ukosefu wa ajira na umaskini",
  "poor infrastructure": "miundombinu duni",
  "Environmental and structural hazards": "Hatari za kimazingira na kimuundo",
  "police-community tensions": "mvutano kati ya polisi na jamii",
  "Funding High school education to minimize dropouts rates": "Kufadhili elimu ya shule ya upili kupunguza viwango vya kuacha shule",
  "Food distribution and feeding programs against poverty issues": "Usambazaji wa chakula na mipango ya chakula dhidi ya umaskini",
  "Empowerment through Moha's Biz Mtaani programs that addresses unemployment, poverty and crime": "Uwezeshaji kupitia mipango ya Moha ya Biz Mtaani inayoshughulikia ukosefu wa ajira, umaskini na uhalifu",
  "Mentorship programs to avoid idleness and back to school sport tournaments ": "Mipango ya ushauri kuepuka uvivu na mashindano ya michezo ya kurudi shule",
  "legal aid on GBV and Funding lawyers to follow family cases": "Msaada wa kisheria kuhusu GBV na kufadhili mawakili kushughulikia mashauri ya familia",
  "Empower and fund reformed drug addicts and criminals": "Kuwezesha na kufadhili waraibu wa dawa na wahalifu waliobadilika",
  "Collaborate with CBOs, NGOs and National Govenment on GBV and rape cases": "Kushirikiana na CBOs, NGOs na Serikali ya Taifa kuhusu kesi za GBV na ubakaji",
  "Initiate more economic and social empowerment programs to tackle unemployment and poverty": "Kuanzisha mipango zaidi ya uwezeshaji wa kiuchumi na kijamii kukabiliana na ukosefu wa ajira na umaskini",
  "Build more access roads, street light installation and open up remote areas": "Kujenga barabara zaidi za kufikia, kuweka taa za barabarani na kufungua maeneo ya mbali",
  "Initiate closer police-community partnership": "Kuanzisha ushirikiano wa karibu zaidi kati ya polisi na jamii",
  "Vulnerable groups without targeted support": "Makundi yaliyo katika hatari bila msaada unaolengwa",
  "Food insecurity in households": "Ukosefu wa chakula katika kaya",
  "Limited access to health insurance registration": "Upatikanaji mdogo wa usajili wa bima ya afya",
  "PWDs lack assistive devices and essential amenities": "Watu wenye ulemavu wanakosa vifaa vya kusaidia na mahitaji muhimu",
  "Support to the vulnerable groups": "Msaada kwa makundi yaliyo katika hatari",
  "Food distribution": "Usambazaji wa chakula",
  "SHA registration": "Usajili wa SHA",
  "Free assistive devices": "Vifaa vya kusaidia bure",
  "Recruitment and industrial attachment opportunities": "Fursa za kuajiriwa na mafunzo ya viwandani",
  "Overseas and International Scholarship": "Udhamini wa masomo ya ng'ambo na kimataifa",
  "Back to school tournaments": "Mashindano ya kurudi shule",
  "Mentorship programs": "Mipango ya ushauri",

  // Donate page
  "Power the Movement": "Nguvu ya Harakati",
  "Every shilling delivers.": "Kila shilingi inawasilisha.",
  "From KSh 500 to KSh 10,000 — your donation funds bursaries, clinics, clean-ups, and youth programs across Mathare.": "Kuanzia KSh 500 hadi KSh 10,000 — mchango wako unafadhili bursary, kliniki, usafi, na mipango ya vijana katika Mathare yote.",
  "Choose an amount (KSh)": "Chagua kiasi (KSh)",
  "Or enter custom amount": "Au weka kiasi chako maalum",
  "M-Pesa Phone Number": "Nambari ya Simu ya M-Pesa",
  "You will receive an STK Push prompt to confirm.": "Utapokea ujumbe wa STK Push kuthibitisha.",
  "Or use Paybill manually:": "Au tumia Paybill mwenyewe:",
  "Cardholder Name": "Jina la Mmiliki wa Kadi",
  "Card Number": "Nambari ya Kadi",
  "Expiry": "Tarehe ya Kumalizika",
  "Secure payment. Your information is never shared.": "Malipo salama. Taarifa yako haitashirikiwa kamwe.",
  "Your Impact": "Athari Yako",
  "Where every shilling goes": "Kila shilingi inaenda wapi",
  "From food parcels to bursaries to clean water tanks — your donation funds the work that's already happening, every single week, on the streets of Mathare.": "Kuanzia vifurushi vya chakula hadi bursary na matanki ya maji safi — mchango wako unafadhili kazi inayoendelea tayari, kila wiki, mitaani mwa Mathare.",
  "Food & relief drives": "Kampeni za chakula na msaada",
  "Clean water tanks": "Matanki ya maji safi",
  "Student bursaries": "Bursary za wanafunzi",
  "Hustler tools & capital": "Zana na mtaji wa hustler",
  "Sending STK Push…": "Inatuma STK Push...",
  "Support Moha": "Msaidie Moha",
  "Processing…": "Inashughulika...",
  "Donate KSh": "Changia KSh",
  "Donate Again": "Changia Tena",
  "Asante Sana": "Asante Sana",
  "You powered the movement": "Ulichochea harakati",
  "Asante kwa kuwa pamoja nasi!": "Asante kwa kuwa pamoja nasi!",
  "is fueling real change in Mathare. We'll send a receipt shortly.": "inachochea mabadiliko halisi Mathare. Tutatuma risiti hivi karibuni.",
  "Your contribution of": "Mchango wako wa",
  "Send SMS": "Tuma SMS",
  "Please select your ward before voting.": "Tafadhali chagua wadi yako kabla ya kupiga kura.",
  "You've already rated this service.": "Umeshakadiriwa huduma hii.",
  "Please enter a valid Kenyan mobile number (07XX or 01XX)": "Tafadhali weka nambari sahihi ya simu ya Kenya (07XX au 01XX)",
  "Thank-you message sent to your number!": "Ujumbe wa shukrani umetumwa kwa nambari yako!",

  // News page
  "The latest from the movement": "Habari mpya zaidi kutoka kwa harakati",
  "Campaign milestones, community wins, and the work happening on the ground every single day.": "Mafanikio ya kampeni, ushindi wa jamii, na kazi inayofanyika nyanjani kila siku.",
  "Featured": "Imeangaziwa",
  "Movement": "Harakati",
  "Health": "Afya",
  "Environment": "Mazingira",
  "Business": "Biashara",
  "Read more": "Soma zaidi",

  // Stories page
  "Voices of Mathare": "Sauti za Mathare",
  "Real people. Real impact.": "Watu halisi. Athari halisi.",
  "These are the stories of mama mbogas, students, elders, and youth whose lives Moha has changed — long before any campaign poster went up.": "Hizi ndizo hadithi za mama mboga, wanafunzi, wazee, na vijana ambao maisha yao yamebadilishwa na Moha — muda mrefu kabla ya bango lolote la kampeni kuwekwa.",

  // Footer
  "A movement for Mathare — building a constituency where every youth, mama, and mzee has dignity, opportunity, and a voice.": "Harakati kwa ajili ya Mathare — kujenga eneo bunge ambapo kila kijana, mama, na mzee ana heshima, fursa, na sauti.",
  "Core Values": "Maadili ya Msingi",
  "Integrity": "Uadilifu",
  "Service": "Huduma",
  "Inclusion": "Ujumuishaji",
  "Accountability": "Uwajibikaji",
  "Hard Work": "Bidii",
  "Unity": "Umoja",
  "PARTNER WITH US": "SHIRIKIANA NASI",
  "Get in Touch": "Wasiliana Nasi",
  "Follow the Movement": "Fuata Harakati",
  "Moha for Mathare. Paid for by friends of Moha.": "Moha kwa Mathare. Imelipwa na marafiki wa Moha.",
  "Built for the people of Mathare. 🇰🇪": "Imejengwa kwa watu wa Mathare. 🇰🇪",
  "Send a Message": "Tuma Ujumbe",

  // Payment methods (advertise page)
  "Cash": "Pesa Taslimu",
  "Paybill": "Paybill",
  "Till Number": "Nambari ya Till",
  "Send Money": "Tuma Pesa",
  "Pochi la Biashara": "Pochi la Biashara",

  // Chat Widget
  "Chat with Moha AI": "Zungumza na Moha AI",
  "Moha AI": "Moha AI",

  // Priorities page — taglines
  "Hustle protected. Capital unlocked.": "Biashara inalindwa. Mtaji unafunguliwa.",
  "Safer streets. Lit estates. Protected families.": "Barabara salama. Makao yenye taa. Familia zinalindwa.",
  "Leaving no one behind. Support that reaches every corner.": "Hakuna anayeachwa nyuma. Msaada unafikia kila pembe.",

  "Karibu! 👋 I'm Moha's AI assistant. Ask me about the manifesto, donations, foundations, or how to get involved. Kuna More na Moha!":
    "Karibu! 👋 Mimi ni msaidizi wa AI wa Moha. Niulize kuhusu ilani, michango, taasisi, au jinsi ya kujiunga. Kuna More na Moha!",
  "What are Moha's priorities?": "Vipaumbele vya Moha ni vipi?",
  "How do I donate?": "Ninachangia vipi?",
  "Tell me about the bursary program": "Nieleze kuhusu mpango wa bursary",
  "Where is Moha's office?": "Ofisi ya Moha iko wapi?",
  "Network error. Please try again.": "Itilafu ya mtandao. Tafadhali jaribu tena.",
  "Something went wrong. Please try again.": "Kuna kitu kimeenda vibaya. Tafadhali jaribu tena.",
  "Yuko Mtandaoni — uliza chochote": "Yuko Mtandaoni — uliza chochote",
  "Online — ask anything": "Yuko Mtandaoni — uliza chochote",
  "Ask Moha AI…": "Muulize Moha AI...",
  "Try asking:": "Jaribu kuuliza:",

  // Advertise page
  "Mathare Business Hub": "Kitovu cha Biashara cha Mathare",
  "Supporting Mathare Businesses — Moha Delivers. List your hustle for free with photos, payment options and delivery info.": "Kusaidia Biashara za Mathare — Moha Anawasilisha. Orodhesha biashara yako bure na picha, njia za malipo na taarifa za uwasilishaji.",
  "Ready to grow your customer base?": "Uko tayari kupanua wateja wako?",
  "List your business in under 2 minutes. Always free.": "Orodhesha biashara yako ndani ya dakika 2. Daima bila malipo.",
  "Advertise Your Business": "Tangaza Biashara Yako",
  "Browse Marketplace": "Vinjari Soko",
  "businesses listed": "biashara zimeorodheshwa",
  "Mathare's": "Soko la",
  "Marketplace": "Mathare",
  "Discover trusted local businesses run by your neighbours. Filter by ward or category to find exactly what you need.": "Gundua biashara za ndani zinazoaminika zinazoendeshwa na majirani zako. Chuja kwa wadi au kategoria kupata unachohitaji.",
  "Search businesses, owners or services...": "Tafuta biashara, wamiliki au huduma...",
  "All Wards": "Wadi Zote",
  "All Categories": "Kategoria Zote",
  "Active filters:": "Vichungi vilivyowezesha:",
  "No businesses match your search": "Hakuna biashara zinazolingana na utafutaji wako",
  "Try clearing filters or be the first to list in this category.": "Jaribu kufuta vichungi au kuwa wa kwanza kuorodhesha katika kategoria hii.",
  "List Your Business": "Orodhesha Biashara Yako",
  "Your hustle deserves to be seen": "Biashara yako inastahili kuonekana",
  "Join hundreds of Mathare entrepreneurs growing their customer base through Moha's free community marketplace.": "Jiunge na mamia ya wajasiriamali wa Mathare wanaokua kupitia soko la bure la jamii la Moha.",
  "Advertise Your Business — Free": "Tangaza Biashara Yako — Bure",
  "Contact via WhatsApp": "Wasiliana kupitia WhatsApp",
  "Share this business": "Shiriki biashara hii",
  "Request edits to this listing": "Omba mabadiliko kwa orodha hii",
  "Request edits to your listing": "Omba mabadiliko kwa orodha yako",
  "Tell the admin what to change about": "Mwambie msimamizi nini cha kubadilisha kuhusu",
  "Your name": "Jina lako",
  "Phone / WhatsApp contact": "Nambari ya Simu / WhatsApp",
  "What needs to change?": "Kitu gani kinahitaji kubadilishwa?",
  "Cancel": "Ghairi",
  "Send request": "Tuma ombi",
  "Ward": "Wadi",
  "Delivery": "Uwasilishaji",
  "Free for every Mathare entrepreneur. Takes about 3 minutes.": "Bure kwa kila mjasiriamali wa Mathare. Inachukua dakika 3 tu.",
  "About You": "Kuhusu Wewe",
  "Location & Contact": "Eneo na Mawasiliano",
  "Payments & Service": "Malipo na Huduma",
  "Photos & Launch": "Picha na Uzinduzi",
  "Your Name *": "Jina Lako *",
  "Business Name *": "Jina la Biashara *",
  "Business Type *": "Aina ya Biashara *",
  "Choose a category": "Chagua kategoria",
  "Website / Social Page (optional)": "Tovuti / Ukurasa wa Mitandao ya Kijamii (hiari)",
  "Your photos will open this link when customers click them.": "Picha zako zitafungua kiungo hiki wateja wanapoibonyeza.",
  "Ward *": "Wadi *",
  "Select your Mathare ward": "Chagua wadi yako ya Mathare",
  "Area / Estate *": "Eneo / Mtaa *",
  "Street / Precise Location": "Barabara / Eneo Halisi",
  "WhatsApp / Phone Contact *": "WhatsApp / Nambari ya Simu *",
  "Additional Contacts (optional)": "Mawasiliano ya Ziada (hiari)",
  "Short Description (optional)": "Maelezo Mafupi (hiari)",
  "What do you sell or offer?": "Unauza au kutoa nini?",
  "Payment Methods Accepted *": "Njia za Malipo Zinazokubaliwa *",
  "Means of Transport": "Njia ya Usafiri",
  "Delivery Available": "Uwasilishaji Unapatikana",
  "Toggle on if you deliver to customers.": "Washa ikiwa unawasilisha kwa wateja.",
  "Business Photos * (up to 5)": "Picha za Biashara * (hadi 5)",
  "Preview:": "Muhtasari:",
  "Business:": "Biashara:",
  "Payments:": "Malipo:",
  "Delivery:": "Uwasilishaji:",
  "Yes": "Ndiyo",
  "JPG or PNG, up to 5MB each. The first photo becomes your cover.": "JPG au PNG, hadi 5MB kila moja. Picha ya kwanza inakuwa jalada lako.",
  "Uploading…": "Inapakia...",
  "Add photo": "Ongeza picha",
  "I have read and understood the data policy. I consent to my business information being displayed publicly on the Mathare Business Hub. *": "Nimesoma na kuelewa sera ya data. Ninakubaliana na taarifa zangu za biashara kuonyeshwa hadharani kwenye Kitovu cha Biashara cha Mathare. *",
  "Back": "Rudi",
  "Next": "Ifuatayo",
  "Publish My Business": "Chapisha Biashara Yangu",
  "Ward / Location": "Wadi / Eneo",
  "Edit request sent to the admin team": "Ombi la mabadiliko limetumwa kwa timu ya msimamizi",
  "Please fill in your name, contact and the changes you need.": "Tafadhali jaza jina lako, mawasiliano na mabadiliko unayohitaji.",

  // Sign In page
  "My Account": "Akaunti Yangu",
  "Just your name and a password — that's it": "Jina lako tu na nenosiri — hiyo tu",
  "Sign in to continue your bursary application": "Ingia ili uendelee na maombi ya bursary",
  "Sign in to list your business on the Mathare Business Hub": "Ingia ili uorodheshe biashara yako kwenye Kitovu cha Biashara cha Mathare",
  "Create Account": "Fungua Akaunti",
  "Full Name": "Jina Kamili",
  "Password": "Nenosiri",
  "Signing in…": "Inaingia...",
  "Don't have an account?": "Huna akaunti?",
  "Create one": "Fungua moja",
  "Confirm Password": "Thibitisha Nenosiri",
  "At least 4 characters": "Angalau herufi 4",
  "Re-enter password": "Weka nenosiri tena",
  "Use your National ID number or phone number as your password — it's something you'll always remember.": "Tumia nambari yako ya Kitambulisho cha Taifa au nambari ya simu kama nenosiri lako — ni kitu utakachokumbuka daima.",
  "Creating account…": "Inaunda akaunti...",
  "Already have an account?": "Una akaunti tayari?",
  "Sign in": "Ingia",
  "Moha Administrator?": "Msimamizi wa Moha?",
  "Admin Sign In": "Ingia kama Msimamizi",
  "Back to home": "Rudi nyumbani",

  // Bursary Application Dialog
  "Constituency Bursary Application Form": "Fomu ya Maombi ya Bursary ya Jimbo",
  "Ward Bursary Application Form — Term 2 (2026/2027). Complete all four sections and download your application form to sign and submit at the Moha Coordination Office, Kiamaiko-Mathare.": "Fomu ya Maombi ya Bursary ya Wadi — Muhula 2 (2026/2027). Kamilisha sehemu zote nne na upakue fomu yako ya maombi ili usaini na kuwasilisha katika Ofisi ya Uratibu ya Moha, Kiamaiko-Mathare.",
  "Application received!": "Maombi yamepokelewa!",
  "Download the pre-filled form, attach the required documents (National ID, birth certificate, fee structure, report form, NCPWD card, etc.), sign, and drop it at the Moha Coordination Office, Kiamaiko-Mathare.": "Pakua fomu iliyojazwa tayari, ambatisha nyaraka zinazohitajika (Kitambulisho cha Taifa, cheti cha kuzaliwa, muundo wa karo, fomu ya ripoti, kadi ya NCPWD, n.k.), saini, na uwasilishe katika Ofisi ya Uratibu ya Moha, Kiamaiko-Mathare.",
  "Know someone who needs to apply? Share this link": "Unajua mtu anayehitaji kuomba? Shiriki kiungo hiki",
  "Copy": "Nakili",
  "Share with friends or family in Mathare who also need bursary support.": "Shiriki na marafiki au familia huko Mathare wanaohitaji pia msaada wa bursary.",
  "Download Application Form (PDF)": "Pakua Fomu ya Maombi (PDF)",
  "Student": "Mwanafunzi",
  "School": "Shule",
  "Guardian": "Mlezi",
  "Review": "Kagua",
  "Student's Details": "Maelezo ya Mwanafunzi",
  "Student name *": "Jina la mwanafunzi *",
  "Full legal name": "Jina kamili la kisheria",
  "Admission / Registration number": "Nambari ya Usajili / Kulazwa",
  "Date of birth": "Tarehe ya kuzaliwa",
  "Gender": "Jinsia",
  "Select": "Chagua",
  "Female": "Mke",
  "Male": "Mume",
  "Grade / Class *": "Darasa *",
  "Select grade": "Chagua darasa",
  "Birth certificate number": "Nambari ya cheti cha kuzaliwa",
  "As on birth certificate": "Kama inavyoonekana kwenye cheti cha kuzaliwa",
  "Student lives with a disability": "Mwanafunzi anaishi na ulemavu",
  "Please specify (NCPWD card / nature of disability)": "Tafadhali eleza (kadi ya NCPWD / aina ya ulemavu)",
  "Student's outstanding ability / achievement": "Uwezo/Mafanikio ya Mwanafunzi",
  "Academic performance, talent, conduct…": "Utendaji wa masomo, kipaji, mwenendo...",
  "Student annual fee payable (KSh)": "Karo ya mwaka ya mwanafunzi (KSh)",
  "Student's outstanding fee balance (KSh)": "Salio la karo la mwanafunzi (KSh)",
  "Amount applying for (KSh)": "Kiasi kinachoombwa (KSh)",
  "Have you ever received a Bursary or support from Moha Foundation or any other public source in the last 6 months?": "Je, umewahi kupokea Bursary au msaada kutoka Taasisi ya Moha au chanzo kingine cha umma katika miezi 6 iliyopita?",
  "If yes, state the source (e.g. Moha Foundation, NG-CDF, Equity Wings)": "Ikiwa ndiyo, taja chanzo (mfano Taasisi ya Moha, NG-CDF, Equity Wings)",
  "Amount received (KSh)": "Kiasi kilichopokelewa (KSh)",
  "School's Details": "Maelezo ya Shule",
  "School name *": "Jina la shule *",
  "School category *": "Kategoria ya shule *",
  "Select category": "Chagua kategoria",
  "County *": "Kaunti *",
  "Select county": "Chagua kaunti",
  "Sub-county *": "Sub-kaunti *",
  "Select sub-county": "Chagua sub-kaunti",
  "Pick county first": "Chagua kaunti kwanza",
  "Year of admission": "Mwaka wa kulazwa",
  "School bank account": "Akaunti ya benki ya shule",
  "Parent / Guardian's Details": "Maelezo ya Mzazi / Mlezi",
  "Parents — alive / deceased": "Wazazi — hai / waliokufa",
  "Father alive": "Baba yu hai",
  "Mother alive": "Mama yu hai",
  "Father's Details": "Maelezo ya Baba",
  "Name": "Jina",
  "Phone contact": "Mawasiliano ya simu",
  "National ID": "Kitambulisho cha Taifa",
  "Occupation": "Kazi",
  "Father lives with a disability": "Baba anaishi na ulemavu",
  "Please specify": "Tafadhali eleza",
  "Mother's Details": "Maelezo ya Mama",
  "Mother lives with a disability": "Mama anaishi na ulemavu",
  "Primary Contactable Parent / Guardian": "Mzazi/Mlezi wa Mawasiliano ya Msingi",
  "Name *": "Jina *",
  "Phone contact *": "Mawasiliano ya simu *",
  "Guardian lives with a disability": "Mlezi anaishi na ulemavu",
  "Residential sub-county": "Sub-kaunti ya makazi",
  "Polling station": "Kituo cha kupiga kura",
  "Number of children in school / University": "Idadi ya watoto shuleni / Chuo Kikuu",
  "Monthly budget (KSh)": "Bajeti ya kila mwezi (KSh)",
  "Brief description of reason for application": "Maelezo mafupi ya sababu ya kuomba",
  "Tell us briefly why you need support…": "Tueleze kwa ufupi kwa nini unahitaji msaada...",
  "Review & Data Consent": "Kagua na Idhini ya Data",
  "Admission No.": "Nambari ya Kulazwa",
  "Birth Cert No.": "Nambari ya Cheti cha Kuzaliwa",
  "School location": "Eneo la shule",
  "Annual fee": "Karo ya mwaka",
  "Outstanding balance": "Salio la deni",
  "Amount requested": "Kiasi kilichoombwa",
  "Ward / Polling": "Wadi / Kituo",
  "Children in school": "Watoto shuleni",
  "Monthly budget": "Bajeti ya kila mwezi",
  "Previous bursary": "Bursary ya awali",
  "Not answered": "Haijaajibiwa",
  "Data Policy & Consent": "Sera ya Data na Idhini",
  "The personal information collected in this form (including names, identification numbers, contact details, and household information) will be used exclusively for the purpose of evaluating and processing your bursary application with the": "Taarifa za kibinafsi zilizokusanywa katika fomu hii (ikiwemo majina, nambari za utambulisho, maelezo ya mawasiliano, na taarifa za kaya) zitatumika peke yake kwa madhumuni ya kutathmini na kushughulikia maombi yako ya bursary na",
  "Your data will be stored securely and will": "Data yako itahifadhiwa kwa usalama na haitashirikiwa",
  "not": "hapana",
  "be shared with third parties without your consent, except where required by law. You have the right to request access to or deletion of your data at any time by contacting us at the Moha Coordination Office, Kiamaiko-Mathare or via": "na watu wengine bila idhini yako, isipokuwa inapohitajika kisheria. Una haki ya kuomba ufikiaji au kufutwa kwa data yako wakati wowote kwa kuwasiliana nasi katika Ofisi ya Uratibu ya Moha, Kiamaiko-Mathare au kupitia",
  "By submitting this application, you confirm that the information provided is true and accurate to the best of your knowledge.": "Kwa kuwasilisha maombi haya, unathibitisha kwamba taarifa zilizotolewa ni za kweli na sahihi kadri unavyojua.",
  "I have read and understood the data policy above. I consent to the collection and use of my personal information for bursary application processing purposes. *": "Nimesoma na kuelewa sera ya data hapo juu. Ninakubaliana na ukusanyaji na matumizi ya taarifa zangu za kibinafsi kwa madhumuni ya kushughulikia maombi ya bursary. *",
  "Submitting…": "Inawasilisha...",
  "Submit Application": "Wasilisha Maombi",
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = localStorage.getItem("moha_lang");
    if (saved === "en" || saved === "sw") {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("moha_lang", lang);
  };

  const t = (text: string): string => {
    if (language === "sw") {
      return swTranslations[text] || text;
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};