/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as PrioritiesRouteImport } from './routes/priorities'
import { Route as PollingRouteImport } from './routes/polling'
import { Route as OpinionRouteImport } from './routes/opinion'
import { Route as NewsRouteImport } from './routes/news'
import { Route as FoundationsRouteImport } from './routes/foundations'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as AdminSupportersRouteImport } from './routes/admin.supporters'
import { Route as AdminSmsRouteImport } from './routes/admin.sms'
import { Route as AdminPollsRouteImport } from './routes/admin.polls'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInboxRouteImport } from './routes/admin.inbox'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminBusinessesRouteImport } from './routes/admin.businesses'
import { Route as AdminBursariesRouteImport } from './routes/admin.bursaries'
import { Route as AdminActivitiesRouteImport } from './routes/admin.activities'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const PrioritiesRoute = PrioritiesRouteImport.update({
  id: '/priorities',
  path: '/priorities',
  getParentRoute: () => rootRouteImport,
} as any)
const PollingRoute = PollingRouteImport.update({
  id: '/polling',
  path: '/polling',
  getParentRoute: () => rootRouteImport,
} as any)
const OpinionRoute = OpinionRouteImport.update({
  id: '/opinion',
  path: '/opinion',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsRoute = FoundationsRouteImport.update({
  id: '/foundations',
  path: '/foundations',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportersRoute = AdminSupportersRouteImport.update({
  id: '/admin/supporters',
  path: '/admin/supporters',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSmsRoute = AdminSmsRouteImport.update({
  id: '/admin/sms',
  path: '/admin/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPollsRoute = AdminPollsRouteImport.update({
  id: '/admin/polls',
  path: '/admin/polls',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/admin/inbox',
  path: '/admin/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBusinessesRoute = AdminBusinessesRouteImport.update({
  id: '/admin/businesses',
  path: '/admin/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBursariesRoute = AdminBursariesRouteImport.update({
  id: '/admin/bursaries',
  path: '/admin/bursaries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivitiesRoute = AdminActivitiesRouteImport.update({
  id: '/admin/activities',
  path: '/admin/activities',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advertise': typeof AdvertiseRoute
  '/ask': typeof AskRoute
  '/donate': typeof DonateRoute
  '/foundations': typeof FoundationsRoute
  '/news': typeof NewsRoute
  '/opinion': typeof OpinionRoute
  '/polling': typeof PollingRoute
  '/priorities': typeof PrioritiesRoute
  '/stories': typeof StoriesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/bursaries': typeof AdminBursariesRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/polls': typeof AdminPollsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/admin/supporters': typeof AdminSupportersRoute
  '/api/chat': typeof ApiChatRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advertise': typeof AdvertiseRoute
  '/ask': typeof AskRoute
  '/donate': typeof DonateRoute
  '/foundations': typeof FoundationsRoute
  '/news': typeof NewsRoute
  '/opinion': typeof OpinionRoute
  '/polling': typeof PollingRoute
  '/priorities': typeof PrioritiesRoute
  '/stories': typeof StoriesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/bursaries': typeof AdminBursariesRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/polls': typeof AdminPollsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/admin/supporters': typeof AdminSupportersRoute
  '/api/chat': typeof ApiChatRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advertise': typeof AdvertiseRoute
  '/ask': typeof AskRoute
  '/donate': typeof DonateRoute
  '/foundations': typeof FoundationsRoute
  '/news': typeof NewsRoute
  '/opinion': typeof OpinionRoute
  '/polling': typeof PollingRoute
  '/priorities': typeof PrioritiesRoute
  '/stories': typeof StoriesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/bursaries': typeof AdminBursariesRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/polls': typeof AdminPollsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/admin/supporters': typeof AdminSupportersRoute
  '/api/chat': typeof ApiChatRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advertise'
    | '/ask'
    | '/donate'
    | '/foundations'
    | '/news'
    | '/opinion'
    | '/polling'
    | '/priorities'
    | '/stories'
    | '/unsubscribe'
    | '/admin/activities'
    | '/admin/bursaries'
    | '/admin/businesses'
    | '/admin/content'
    | '/admin/inbox'
    | '/admin/login'
    | '/admin/polls'
    | '/admin/sms'
    | '/admin/supporters'
    | '/api/chat'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advertise'
    | '/ask'
    | '/donate'
    | '/foundations'
    | '/news'
    | '/opinion'
    | '/polling'
    | '/priorities'
    | '/stories'
    | '/unsubscribe'
    | '/admin/activities'
    | '/admin/bursaries'
    | '/admin/businesses'
    | '/admin/content'
    | '/admin/inbox'
    | '/admin/login'
    | '/admin/polls'
    | '/admin/sms'
    | '/admin/supporters'
    | '/api/chat'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/advertise'
    | '/ask'
    | '/donate'
    | '/foundations'
    | '/news'
    | '/opinion'
    | '/polling'
    | '/priorities'
    | '/stories'
    | '/unsubscribe'
    | '/admin/activities'
    | '/admin/bursaries'
    | '/admin/businesses'
    | '/admin/content'
    | '/admin/inbox'
    | '/admin/login'
    | '/admin/polls'
    | '/admin/sms'
    | '/admin/supporters'
    | '/api/chat'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvertiseRoute: typeof AdvertiseRoute
  AskRoute: typeof AskRoute
  DonateRoute: typeof DonateRoute
  FoundationsRoute: typeof FoundationsRoute
  NewsRoute: typeof NewsRoute
  OpinionRoute: typeof OpinionRoute
  PollingRoute: typeof PollingRoute
  PrioritiesRoute: typeof PrioritiesRoute
  StoriesRoute: typeof StoriesRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AdminActivitiesRoute: typeof AdminActivitiesRoute
  AdminBursariesRoute: typeof AdminBursariesRoute
  AdminBusinessesRoute: typeof AdminBusinessesRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminInboxRoute: typeof AdminInboxRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPollsRoute: typeof AdminPollsRoute
  AdminSmsRoute: typeof AdminSmsRoute
  AdminSupportersRoute: typeof AdminSupportersRoute
  ApiChatRoute: typeof ApiChatRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priorities': {
      id: '/priorities'
      path: '/priorities'
      fullPath: '/priorities'
      preLoaderRoute: typeof PrioritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polling': {
      id: '/polling'
      path: '/polling'
      fullPath: '/polling'
      preLoaderRoute: typeof PollingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opinion': {
      id: '/opinion'
      path: '/opinion'
      fullPath: '/opinion'
      preLoaderRoute: typeof OpinionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations': {
      id: '/foundations'
      path: '/foundations'
      fullPath: '/foundations'
      preLoaderRoute: typeof FoundationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/supporters': {
      id: '/admin/supporters'
      path: '/admin/supporters'
      fullPath: '/admin/supporters'
      preLoaderRoute: typeof AdminSupportersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sms': {
      id: '/admin/sms'
      path: '/admin/sms'
      fullPath: '/admin/sms'
      preLoaderRoute: typeof AdminSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/polls': {
      id: '/admin/polls'
      path: '/admin/polls'
      fullPath: '/admin/polls'
      preLoaderRoute: typeof AdminPollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/admin/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/businesses': {
      id: '/admin/businesses'
      path: '/admin/businesses'
      fullPath: '/admin/businesses'
      preLoaderRoute: typeof AdminBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bursaries': {
      id: '/admin/bursaries'
      path: '/admin/bursaries'
      fullPath: '/admin/bursaries'
      preLoaderRoute: typeof AdminBursariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activities': {
      id: '/admin/activities'
      path: '/admin/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AdminActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvertiseRoute: AdvertiseRoute,
  AskRoute: AskRoute,
  DonateRoute: DonateRoute,
  FoundationsRoute: FoundationsRoute,
  NewsRoute: NewsRoute,
  OpinionRoute: OpinionRoute,
  PollingRoute: PollingRoute,
  PrioritiesRoute: PrioritiesRoute,
  StoriesRoute: StoriesRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AdminActivitiesRoute: AdminActivitiesRoute,
  AdminBursariesRoute: AdminBursariesRoute,
  AdminBusinessesRoute: AdminBusinessesRoute,
  AdminContentRoute: AdminContentRoute,
  AdminInboxRoute: AdminInboxRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPollsRoute: AdminPollsRoute,
  AdminSmsRoute: AdminSmsRoute,
  AdminSupportersRoute: AdminSupportersRoute,
  ApiChatRoute: ApiChatRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
